apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: example
  labels:
    tier: database
    stage: example
spec:
  containers:
    - name: db
      image: pobedos/test-db:latest
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: example
  labels:
    tier: service
    stage: example
spec:
  selector:
    tier: database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  namespace: example
  labels:
    tier: backend
    stage: example
spec:
  template:
    metadata:
      labels:
        tier: backend
        stage: example
    spec:
      containers:
        - name: backend-test
          image: pobedos/backend:latest
  selector:
    matchLabels:
      tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: example
  labels:
    tier: service
    stage: example
spec:
  selector:
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080