apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres
    test-part: integration
spec:
  containers:
    - name: db
      image: pobedos/test-db:latest
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: postgres-service
    test-part: intergration
spec:
  selector:
    name: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-test
spec:
  template:
    spec:
      containers:
        - name: backend-test
          image: pobedos/backend-int:latest
      restartPolicy: Never
  backoffLimit: 1
