apiVersion: batch/v1
kind: Job
metadata:
  name: backend-test
spec:
  template:
    spec:
      containers:
        - name: backend-test
          image: pobedos/backend-unit:latest
      restartPolicy: Never
  backoffLimit: 1
