version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
      image: library:latest2
      volumes:
        - ~/temp:/usr/src/myapp/target
volumes:
  db:

