FROM openjdk:17
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN ./gradlew  --refresh-dependencies resolveDependencies
CMD ./gradlew --offline test --tests "ru.pobedonostsev.library.integration.*Test"
