create table author
(
    id          bigint generated by default as identity
        constraint author_pkey
            primary key,
    birth_day   date,
    description text,
    first_name  varchar(20) not null,
    last_name   varchar(20) not null,
    patronymic  varchar(20)
);

alter table author
    owner to postgres;

create table book
(
    id          bigint generated by default as identity
        constraint book_pkey
            primary key,
    description text,
    name        varchar(50) not null
        constraint uk_wugryet8mf6oi28n00x2eoc4
            unique
);

alter table book
    owner to postgres;

create table book_author
(
    book_id    bigint not null
        constraint fkhwgu59n9o80xv75plf9ggj7xn
            references book,
    authors_id bigint not null
        constraint fkee8x5xlovy8tlylr5ag6yruxd
            references author
);

alter table book_author
    owner to postgres;

create table genre
(
    id   bigint generated by default as identity
        constraint genre_pkey
            primary key,
    name varchar(20) not null
        constraint uk_ctffrbu4484ft8dlsa5vmqdka
            unique
);

alter table genre
    owner to postgres;

create table book_genre
(
    book_id   bigint not null
        constraint fk52evq6pdc5ypanf41bij5u218
            references book,
    genres_id bigint not null
        constraint fkpi0ukki18qak436won883bn10
            references genre
);

alter table book_genre
    owner to postgres;
